Update wm/pekwm to 0.1.17.
pkgsrc changes:
---------------
Fetch over https using curl.

Upstream changes:
-----------------
Bugs fixed

    #235 "GotoClientID does not work if switch workspace." reported by Markand
and fixed by Andreas Schlick.

    #286 "Funky behaviors of FocusDirectional" reported by b4283 and fixed by
Andreas Schlick.

    #317 "Shape masks are defined by image alpha>50% -- sometimes this is
wrong" reported by rtollert and fixed by Andreas Schlick.

    #318 "x11.cc:1005:9: erreur: #pragma GCC diagnostic not allowed inside
functions" reported and fixed by wallex.

    #319 "data/scripts/Makefile breaks when building out of the source tree"
reported and fixed by Ondrej Kubecka.

    #321 "DisallowedActions - Close doesn't work (0.1.16)" reported by cico and
fixed by Andreas Schlick.

    #323 "Infinite loop if screen's visual is PsuedoColor" reported by Jari
Aalto and fixed by Andreas Schlick.

    "x11.cc compilation error without XShape" reported by Martin Åkerström.

    "Crash on empty menus after reload". Reported by Martin Åkerström and
fixed by Claes Nästén and Andreas Schlick.

    Improve placement of windows skipping heads with fullscreen windows. Claes
Nästén and Andreas Schlick

User visible changes

    New SetGeometry action for moving/resizing a Frame to a fixed position.
    New MoveToHead action for moving a Frame between heads.

Configuration changes
Miscellaneous changes

    Added pekwm_screenshot.sh that takes screenshots using scrot, ImageMagick
or xwd+netpbm. Available via the keybinding Alt + PrintScreen or the root menu.
    Removed undocumented HarbourMenu (if it ever worked for you, write me :-)